### ISSUE TITLE
Invalid URI error for valid file

### ISSUE THREAD

**Issue by wouterbeek** [rdfjs/rdfxml-streaming-parser.js#17]
Parsing [this RDF/XML file](http://purl.org/vocab/frbr/frbr-core-20050810.rdf) emits the following error:

```
Error: Invalid URI: 
    at RdfXmlParser.uriToNamedNode (/home/wbeek/triply/rdfxml-streaming-parser.js/node_modules/rdfxml-streaming-parser/lib/RdfXmlParser.js:176:19)
    at RdfXmlParser.valueToUri (/home/wbeek/triply/rdfxml-streaming-parser.js/node_modules/rdfxml-streaming-parser/lib/RdfXmlParser.js:163:21)
    at RdfXmlParser.onTagResource (/home/wbeek/triply/rdfxml-streaming-parser.js/node_modules/rdfxml-streaming-parser/lib/RdfXmlParser.js:345:73)
    at RdfXmlParser.onTag (/home/wbeek/triply/rdfxml-streaming-parser.js/node_modules/rdfxml-streaming-parser/lib/RdfXmlParser.js:241:18)
    at SAXStream.emit (events.js:198:13)
    at SAXParser.me._parser.(anonymous function) [as onopentag] (/home/wbeek/triply/rdfxml-streaming-parser.js/node_modules/sax/lib/sax.js:258:17)
    at emit (/home/wbeek/triply/rdfxml-streaming-parser.js/node_modules/sax/lib/sax.js:624:35)
    at emitNode (/home/wbeek/triply/rdfxml-streaming-parser.js/node_modules/sax/lib/sax.js:629:5)
    at openTag (/home/wbeek/triply/rdfxml-streaming-parser.js/node_modules/sax/lib/sax.js:825:5)
    at SAXParser.write (/home/wbeek/triply/rdfxml-streaming-parser.js/node_modules/sax/lib/sax.js:1391:13)
```

The file parses correctly in Raptor.

**Comment by rubensworks** [comment]
Fixed in 1.3.0.
