### ISSUE TITLE
ParseError for valid RDF/XML?

### ISSUE THREAD

**Issue by blake-regalia** [rdfjs/rdfxml-streaming-parser.js#31]
This only seems to happen when using a default namespace, i.e., `xmlns="..."`, in combination with a scoped namespace declaration, e.g., `ns0:hasBlankNode xmlns:ns0="..."`.  The example here is about `rdf:nodeID` and the same error happens for languaged literals and datatyped literals since they also have required attributes.

```js
const xml_rdf_parser = require('rdfxml-streaming-parser').RdfXmlParser;

let y_parser = new xml_rdf_parser();

y_parser.on('data', (g_quad) => {
  console.log(g_quad);
});

y_parser.on('error', (e_parse) => {
  throw e_parse;
});

y_parser.end(/* syntax: rdf/xml */ `
  <?xml version="1.0" encoding="utf-8"?>
  <rdf:RDF
    xmlns="http://ex.org/o/"
    xmlns:rdf="http://www.w3.org/1999/02/22-rdf-syntax-ns#">

    <rdf:Description rdf:about="http://ex.org/i/subject">
      <rdf:type rdf:resource="http://ex.org/o/type"/>
      <hasBlankNode rdf:nodeID="orange"/>
      <ns0:hasBlankNode xmlns:ns0="http://anon.org/o/" rdf:nodeID="yellow"/>
    </rdf:Description>

  </rdf:RDF>
`);
```

throws:
```
ParseError: Found both non-rdf:* property attributes and rdf:nodeID (yellow).
    at RdfXmlParser.newParseError (/app/rdfxml-streaming-parser/lib/RdfXmlParser.js:140:16)
    at RdfXmlParser.onTagProperty (/app/rdfxml-streaming-parser/lib/RdfXmlParser.js:449:40)
    at RdfXmlParser.onTag (/app/rdfxml-streaming-parser/lib/RdfXmlParser.js:233:18)
    at SAXStream.emit (events.js:315:20)
    at SAXParser.me._parser.<computed> [as onopentag] (/app/sax/lib/sax.js:258:17)
    at emit (/app/sax/lib/sax.js:624:35)
    at emitNode (/app/sax/lib/sax.js:629:5)
    at openTag (/app/sax/lib/sax.js:825:5)
    at SAXParser.write (/app/sax/lib/sax.js:1292:13)
    at SAXStream.write (/app/sax/lib/sax.js:239:18)
```

**Comment by rubensworks** [comment]
Hmm, I thought I fixed this in 6913fa1ffea102ba9c35743fc769961cc47d816f.
Looks like I may have a missed an edge-case.

**Comment by rubensworks** [comment]
@blake-regalia Are you sure you are using the latest version (1.3.4)?
As you can see in this [unit test](https://github.com/rdfjs/rdfxml-streaming-parser.js/commit/8bfc8a9e309b9ea7d67924f807e5827e1c8d2f76) your example appears to be working fine.

**Comment by blake-regalia** [comment]
Ahh, yes it seems most likely that was the case... before my node_modules directory had sync'd. My apologies!
